<?php

/**
 * Lombardia Informatica S.p.A.
 * OPEN 2.0
 *
 *
 * @package    lispa\amos\admin\assets
 * @category   CategoryName
 */

namespace lispa\amos\admin\assets;

use yii\web\AssetBundle;
use lispa\amos\core\widget\WidgetAbstract;


/**
 * Class ModuleAdminAsset
 * @package lispa\amos\admin\assets
 */
class ModuleAdminAsset extends AssetBundle
{
    public $sourcePath = '@vendor/lispa/amos-admin/src/assets/web';

    public $css = [
        'less/admin.less',
    ];
    public $js = [
        //'js/admin-js.js'
    ];
    public $depends = [
    ];

    public function init()
    {
        $moduleL = \Yii::$app->getModule('layout');

        if(!empty(\Yii::$app->params['dashboardEngine']) && \Yii::$app->params['dashboardEngine'] == WidgetAbstract::ENGINE_ROWS){
            $this->css = ['less/admin_fullsize.less','less/widget_users_list.less'];
            $this->js = ['js/widget_users_list.js'];
        }

        if(!empty($moduleL))
        { $this->depends [] = 'lispa\amos\layout\assets\BaseAsset'; }
        else
        { $this->depends [] = 'lispa\amos\core\views\assets\AmosCoreAsset'; }
        parent::init(); // TODO: Change the autogenerated stub
    }

}
