<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    open20\amos\admin\assets
 * @category   CategoryName
 */

namespace open20\amos\admin\assets;

use yii\web\AssetBundle;

/**
 * Class ModuleSearchAsset
 * @package open20\amos\admin\assets
 */
class ModuleSearchAsset extends AssetBundle
{
    public $sourcePath = '@vendor/open20/amos-admin/src/assets/web';

    public $css = [
    ];
    public $js = [
        'js/search-js.js'
    ];
    public $depends = [
    ];

    public function init()
    {
        $moduleL = \Yii::$app->getModule('layout');
        if(!empty($moduleL))
        { $this->depends [] = 'open20\amos\layout\assets\BaseAsset'; }
        else
        { $this->depends [] = 'open20\amos\core\views\assets\AmosCoreAsset'; }
        parent::init(); // TODO: Change the autogenerated stub
    }

}
